//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFSerBIpagos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tags
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tags()
        {
            this.OperacionesSerBIpagos = new HashSet<OperacionesSerBIpagos>();
        }
    
        public long Id { get; set; }
        public string NumTag { get; set; }
        public string SaldoTag { get; set; }
        public bool StatusTag { get; set; }
        public bool StatusResidente { get; set; }
        public System.DateTime DateTTag { get; set; }
        public long CuentaId { get; set; }
        public string IdCajero { get; set; }
    
        public virtual CuentasTelepeajes CuentasTelepeajes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperacionesSerBIpagos> OperacionesSerBIpagos { get; set; }
    }
}
